stages:
  cleanup:
    cmd: py src/models/CleanUpDf.py
    deps:
    - data/raw/04_cricket_1999to2011.csv
    - src/models/CleanUpDf.py
    outs:
    - data/interim/temp4:
        persist: true


  feature:
    cmd: py src/models/FeatureArrays.py
    deps:
    - data/interim/temp4
    - src/models/FeatureArrays.py
    outs:
    - data/interim/temp5:
        persist: true
    - data/interim/temp6:
        persist: true

  train:
    cmd: py src/models/TrainModel.py
    deps:
    - src/models/TrainModel.py
    - data/interim/temp5
    - data/interim/temp6
    metrics:
    - reports/results.json:
        persist: true

